- hosts: all
  become: yes
  tasks:
    - name: Run kubeadm reset
      shell: kubeadm reset -f

    - name: get user home directory
      shell: >
             getent passwd smiano | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home

    - name: debug output
      debug:
        var: user_home.stdout

    - name: Cleanup home
      ansible.builtin.file:
        path: "{{ user_home.stdout }}/.kube"
        state: "absent"

    - name: Reset CNI config
      ansible.builtin.file:
        path: "/etc/cni/net.d"
        state: "absent"

    - name: Clean up node_local_ip
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/node_local_ip.txt"
        state: "absent"

    - name: Clean up disable_ht
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/disable_ht.txt"
        state: "absent"
    
- hosts: master
  become: yes
  tasks:
    - name: Clean up cluster initialized
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/cluster_initialized.txt"
        state: "absent"

- hosts: workers
  become: yes
  tasks:
    - name: Clean up node_joined
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/node_joined.txt"
        state: "absent"
        
    - name: Clean up label_worker_nodes
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/label_worker_nodes.txt"
        state: "absent"