- hosts: master
  become: yes
  tasks:
    - name: remove swap
      shell: "swapoff -a"

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: smiano
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
      
    - name: get user home directory
      shell: >
             getent passwd smiano | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home

    - name: debug output
      debug:
        var: user_home.stdout

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ user_home.stdout }}/.kube/config"
        remote_src: yes
        owner: smiano