- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: remove swap
      shell: "swapoff -a"

    - name: join cluster	
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: all
  become: yes
  tasks:
    - name: use local ips
      shell: "{{ local_ip_path | default('/local/') }}use-local-ips.sh {{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} >> node_local_ip.txt"
      args:
        chdir: $HOME
        creates: node_local_ip.txt

- hosts: all
  become: yes
  tasks:
    - name: Disable HT
      shell: "{{ disable_ht | default('/local/') }}disable_ht.sh >> disable_ht.txt"
      args:
        chdir: $HOME
        creates: disable_ht.txt