name: Morpheus K8s Build Docker

on:
  push:
    branches:
      - 'morpheus-k8s'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: morpheuscompiler/morpheus-polycube-k8s:latest
          build-args: |
            DEFAULT_MODE=morpheus-k8s 
            DEFAULT_CLONE_MODE=local